baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Drew Kramer"
pluralizelisttitles = false

enableEmoji = true

[author]
  name = "Drew Kramer"

[params]
  description = ""
  strapline = "UI/UX Design & Development"
  location = "Lancaster, PA"
  twitter = "@drewkramer"
  # Set Cloudinary URL for image hosting
  cloudinary_url = "https://res.cloudinary.com/drewkramer/image/upload"
  author = "Drew Kramer"

[[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 15